# Alexa Prompts Language Constants

WELCOME_MSG = "WELCOME_MSG"
WELCOME_REMPROMPT_MSG = "WELCOME_REMPROMPT_MSG"
WELCOME_BACK_MSG = "WELCOME_BACK_MSG"
WELCOME_BACK_MSG_plural = "WELCOME_BACK_MSG_plural"
HAPPY_BIRTHDAY_MSG = "HAPPY_BIRTHDAY_MSG"
REGISTER_BIRTHDAY_MSG = "REGISTER_BIRTHDAY_MSG"
HELP_MSG = "HELP_MSG"
GOODBYE_MSG = "GOODBYE_MSG"
ERROR_MSG = "ERROR_MSG"
ERROR_TIMEZONE_MSG = "ERROR_TIMEZONE_MSG"
